### ISSUE TITLE
Configuration settings are not getting saved in jenkins for this plugin

### ISSUE THREAD

**Issue by amanscollection** [melezhik/chef-plugin#4]
Hi,
I have installed this plugin to jenkins and configure the ssh details as suggested.
But after clicking on save button in jenkins job, the configuration details wiped out and if i again click on configure job to change the chef-client details it is not showing me any previous entered details.
![chef-client](https://cloud.githubusercontent.com/assets/8632562/6210691/191457fa-b5f8-11e4-8d63-b92c007e7fb0.jpg)

attaching a screenshot.
Please suggest.

Regards
Amandeep Singh

**Comment by melezhik** [comment]
Ok. Which version of Jenkins do you use?

**Comment by amanscollection** [comment]
Hi,

I am using jenkins 1.598 version.

Regards
Amandeep Singh

**Comment by melezhik** [comment]
Ok, and one more question ... Ruby-runtime plugin version?

**Comment by nikki-rally** [comment]
Hi,

Just wanted to let you know that we are seeing this same behavior both with this chef-plugin and with our own plugin that relies on the ruby-runtime plugin. We are seeing this in Jenkins >= 1.598 and ruby-runtime 0.12 . Still trying to track down the root cause ourselves.

Nikki

**Comment by melezhik** [comment]
Hi Nikki! This is very close to what I be been think about, something hidden in ruby runtime and Jenkins cooperation , ... We also have not copied with this issue , and just sticked to certain versions ...

**Comment by plorent** [comment]
Having the same issue with Jenkins 1.606 and Ruby runtime 0.12
Can you maybe post information on which version of Jenkins to use to get the Chef plugin running properly?

**Comment by melezhik** [comment]
You may exact version of   'ruby-runtime' -  '0.10'. I do not think it relates to the version of Jenkins somehow, at least first you may start with version of ruby- runtime

**Comment by plorent** [comment]
I've tried installing ruby-runtime 0.10 on Jenkins 1.606 but that fails. Running ruby-runtime 0.12 I get the following error:
Apr 01, 2015 9:44:37 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin chef
java.io.IOException: Dependency ruby-runtime (0.10) doesn't exist
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:480)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:369)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:903)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

And in your code you are declaring a dependency on ruby-runtime 0.10:
plugin.depends_on 'ruby-runtime', '0.10'
Would '~> 0.10' work here?

**Comment by melezhik** [comment]
You should probably downgrade jenkins ruby-runtime plugin to 0.10 version.


2015-04-01 11:40 GMT+03:00 Peter Lorent <notifications@github.com>:

**Comment by melezhik** [comment]
@piorent, I have investigated the issue again. My resume.
- plugin works fine ( let you save parameters ) on ruby-runtime 0.12 
- ruby-runtime 0.10 is not installable into fresh jenkins and should not be taken into account   ( although I use ruby-runtime 0.10 when develop plugin via jpi, using pretty old jenkins )
- plugin.depends_on 'ruby-runtime', '0.10' would work fine when you have ruby-runtime 0.12 pre installed ( ~ does not make a sense in jpi dependency manager )
- I am going to release new version of plugin which depends_on 'ruby-runtime', '0.12' to make it clear ...
