### ISSUE TITLE
Facing error in configuring chef plugin in jenkins

### ISSUE THREAD

**Issue by amanscollection** [melezhik/chef-plugin#5]
Hi,

I am not able to configure the chef plugin for running chef-client at remote machine.
Please refer to the attachment for screenshots.
SSH host - giving IP of the remote machine.
SSH Login-: Username
![s1](https://cloud.githubusercontent.com/assets/8632562/6390905/b7613e4c-bdd6-11e4-9b66-0546a1481ea7.png)
![s2](https://cloud.githubusercontent.com/assets/8632562/6390910/be992288-bdd6-11e4-8731-809d484390fc.png)

Regards
Amandeep Singh

**Comment by melezhik** [comment]
Hi. Yes, as I can see from console log you have attached there is no bash
executable available in a system path on target machine. Is it running
under windows OS?

четверг, 26 февраля 2015 г. пользователь amanscollection написал:

> Hi,
>
> I am not able to configure the chef plugin for running chef-client at
> remote machine.
> Please refer to the attachment for screenshots.
> SSH host - giving IP of the remote machine.
> SSH Login-: Username
> [image: s1]
> <https://cloud.githubusercontent.com/assets/8632562/6390905/b7613e4c-bdd6-11e4-9b66-0546a1481ea7.png>
> [image: s2]
> <https://cloud.githubusercontent.com/assets/8632562/6390910/be992288-bdd6-11e4-8731-809d484390fc.png>
>
> Regards
> Amandeep Singh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/melezhik/chef-plugin/issues/5>.
>


-- 
Отправлено с мобильного устройства

**Comment by amanscollection** [comment]
Hi,

Yes jenkin is running on windows OS. and remote host is ubuntu 12 OS.

**Comment by melezhik** [comment]
Bash is required to be installed on remote host to run chef client. 
I know this might be the matter of discuss but now this is the current implementation.
