### ISSUE TITLE
Error in running chef-client on remote machine - 'sorry, you must have a tty to run sudo'

### ISSUE THREAD

**Issue by ghost** [melezhik/chef-plugin#8]
Console Log below:

```
$ bash -c "ssh -o 'StrictHostKeyChecking no' -i /Users/Shared/Jenkins/xxx.pem centos@yyyy.zzzz 'sudo chef-client --force-formatter -l info -j /tmp/default-by-centos-chef.json   '"
sudo: sorry, you must have a tty to run sudo
```

**Comment by melezhik** [comment]
Hi @avinashkolluru , I am not sure if this issue relates to the plugin itself, please take a look at http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password - to get know what you could do with this

**Comment by ghost** [comment]
Thanks @melezhik 
Closing this
